[profile.default]
auto_detect_solc = true
src = "src"
out = "out"
libs = ["lib"]
remappings = [
    "@forge/=lib/forge-std/",
    "@oz/=lib/openzeppelin-contracts/", 
    "@chainlink/=lib/chainlink",
    "@devops/=lib/foundry-devops"
]

[invariant]
runs = 128
depth = 128
fail_on_revert = false

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
